module Utils
  module TechStack
    TECH_STACK = {
      programming_languages: [
        "JavaScript", "HTML/CSS", "HTML", "CSS", "SQL", "Python", "Bash/Shell", "Bash", "Shell", "TypeScript",
        "Java", "C#", "C++", "PowerShell", "C", "PHP", "Go", "Rust", "Kotlin",
        "Lua", "Assembly", "Ruby", "Dart", "Swift", "R", "Groovy", "Visual Basic (.Net)",
        "VBA", "MATLAB", "Perl", "GDScript", "Elixir", "Scala", "Delphi", "Lisp",
        "MicroPython", "Zig", "Erlang", "Fortran", "Ada", "F#", "OCaml", "Gleam",
        "Prolog", "COBOL", "Mojo"
      ],
      frameworks: [
        'Node.js',
        'React',
        'jQuery',
        'Next.js',
        'Express',
        'ASP.NET Core',
        'Angular',
        'Vue.js',
        'FastAPI',
        'Spring Boot',
        'Flask',
        'ASP.NET',
        'WordPress',
        'Django',
        'Laravel',
        'AngularJS',
        'Svelte',
        'Blazor',
        'NestJS',
        'Ruby on Rails',
        'RoR',
        'Rails',
        'Astro',
        'Deno',
        'Symfony',
        'Nuxt.js',
        'Fastify',
        'Axum',
        'Phoenix',
        'Drupal'
      ],
      other_tech_stack: [
        'PostgreSQL',
        'SQLite',
        'Redis',
        'MySQL',
        'MongoDB',
        'Microsoft SQL Server',
        'Elasticsearch',
        'MariaDB',
        'DynamoDB',
        'Supabase',
        'DuckDB',
        'BigQuery',
        'Oracle',
        'Valkey',
        'Cassandra',
        'Snowflake',
        'Firebase Realtime Database',
        'Cosmos DB',
        'Cloud Firestore',
        'Neo4J',
        'Databricks SQL',
        'Clickhouse',
        'InfluxDB',
        'Amazon Redshift',
        'CockroachDB',
        'H2',
        'Pocketbase',
        'Microsoft Access',
        'IBM DB2',
        'Datomic',
        'Docker',
        'Amazon Web Services (AWS)',
        'Kubernetes',
        'npm',
        'Pip',
        'Vite',
        'Microsoft Azure',
        'Google Cloud',
        'Cloudflare',
        'Terraform',
        'Homebrew',
        'Cargo',
        'Make',
        'APT',
        'NuGet',
        'Podman',
        'Prometheus',
        'Ansible',
        'pnpm',
        'Firebase',
        'Yarn',
        'Maven (build tool)',
        'Gradle',
        'Digital Ocean',
        'Vercel',
        'Composer',
        'Pacman',
        'Bun',
        'Datadog',
        'Webpack',
        'MSBuild',
        'Supabase',
        'Chocolatey',
        'Poetry',
        'Netlify',
        'Ninja',
        'Heroku',
        'Splunk',
        'New Relic',
        'IBM Cloud',
        'Railway',
        'Yandex Cloud',
        'ClickHouse',
        'Redpanda',
        'Tailwind'
      ]}.freeze
  end
end
